export const EVENTBRITE_API_KEY = "MHC7SVBQGGWMVC5PCD";
export const EVENTBRITE_CLIENT_SECRET =
  "4SIQK64CLDG5LQS4T3QTPO3JHVISMKVWX2Z6WOC3MK7AL364HY";
export const EVENTBRITE_PRIVATE_TOKEN = "2S2PLNF4LRITQ62A2SKO";
export const EVENTBRITE_PUBLIC_TOKEN = "RPQ7IJEVPHQ3TVHJOMJP";

export const EVENTBRITE_ENDPOINTS = {
  BASE_URI: "https://www.eventbriteapi.com/",
  GET_OBTAIN_ORGANIZATION: "v3/users/me/organizations/",
};

export const EVENTBRITE_TIMEZONE = "America/Los_Angeles";
export const EVENTBRITE_CURRENCY = "USD";
